<script lang="ts">
	import { useI18n } from '$state';
	const i18n = useI18n();

	import Footer from '$organisms/Footer.organism.svelte';
	import pkg from '../../../package.json';
	import { trackEvent } from '$lib/analytics';

	const fullVersion = pkg.version;
	const handleSupportTicketClick = () => {
		trackEvent('outbound_link_click', { link_id: 'support_ticket' });
	};
	const handleHallOfTheGodsClick = () => {
		trackEvent('outbound_link_click', { link_id: 'hall_of_the_gods' });
	};
	const handleMyCompassClick = () => {
		trackEvent('outbound_link_click', { link_id: 'my_compass_consulting' });
	};
</script>

<svelte:head>
	<title>{i18n.t('routes.terms.title')} — Remarkably Organized</title>
</svelte:head>

<main class="legal-page">
	<div class="glass-container">
		<h1>{i18n.t('routes.terms.title')}</h1>
		<p>Last updated: June 2026</p>

		<h2>1. Acceptance of Terms</h2>
		<p>
			By accessing and using Remarkably Organized, you accept and agree to be bound by the
			terms and provision of this agreement.
		</p>

		<h2>2. Description of Service</h2>
		<p>
			Remarkably Organized is a free, browser-based tool that allows users to generate
			custom PDF planners for e-ink tablets. We reserve the right to modify or
			discontinue, temporarily or permanently, the service with or without notice.
		</p>

		<h2>3. Provided "As-Is" / Limitation of Liability</h2>
		<p>
			THE SOFTWARE AND SERVICE ARE PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
			OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS
			FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR
			COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
			ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
			THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.
		</p>
		<p>
			By using this tool, you acknowledge that bugs, calculation errors, or formatting
			issues may occur. You are solely responsible for verifying the accuracy of dates,
			holidays, and layouts in the generated PDFs before relying on them. We are not
			liable for missed appointments, scheduling errors, or any damages arising from the
			use of planners generated by this tool.
		</p>

		<h2>4. Third-Party Services & Device Integration</h2>
		<p>
			Remarkably Organized is an independent, browser-based PDF generation tool. We are
			not affiliated with, endorsed by, or connected to reMarkable AS or any other e-ink
			tablet manufacturer.
		</p>
		<p>
			We <strong>do not</strong>
			interact with the reMarkable cloud API, we
			<strong>do not</strong>
			use OTP codes to register as a device, and we
			<strong>do not</strong>
			have any access to your tablet or personal account. Because our service simply produces
			a downloadable PDF file, using our tool does not require you to violate Section 1 (or
			any other section) of the reMarkable Terms of Service regarding reverse engineering or
			unauthorized API access. The transfer of the generated PDF to your device is done entirely
			by you, using official software.
		</p>

		<h2>5. Copyright & Open Source</h2>
		<p>
			Remarkably Organized is built upon an open-source core originally developed by Brian
			Schwabauer under the MIT License. Significant modifications, features, and hosting
			are architected by XP @ My Compass Consulting, with intellectual property rights
			owned by Hall of the Gods Inc. You may not use our branding, logos, or modified UI
			designs without permission.
		</p>

		<a href="/" class="back-link">← Back to Home</a>
	</div>
	<Footer
		{fullVersion}
		{handleSupportTicketClick}
		{handleHallOfTheGodsClick}
		{handleMyCompassClick} />
</main>

<style lang="scss">
	.legal-page {
		min-height: 100vh;
		background-color: #00326e;
		background-image: linear-gradient(135deg, #012b67 0%, #01559d 50%, #0184ba 100%);
		display: flex;
		justify-content: center;
		padding: 4rem 1rem 6rem;
		position: relative;
		font-family: var(--font-body, system-ui, sans-serif);
	}

	.glass-container {
		background: rgba(255, 255, 255, 0.08);
		backdrop-filter: blur(12px);
		-webkit-backdrop-filter: blur(12px);
		border: 1px solid rgba(255, 255, 255, 0.15);
		border-radius: 20px;
		box-shadow: 0 8px 32px rgba(0, 0, 0, 0.15);
		padding: 3rem;
		max-width: 800px;
		width: 100%;
		color: white;

		h1 {
			margin-top: 0;
			font-size: 2.5rem;
			font-weight: 900;
			text-shadow: 0 2px 4px rgba(0, 0, 0, 0.3);
		}

		h2 {
			font-size: 1.5rem;
			margin-top: 2rem;
			margin-bottom: 0.5rem;
			color: #fcd34d;
		}

		p {
			line-height: 1.6;
			opacity: 0.9;
			margin-bottom: 1rem;
		}

		.back-link {
			display: inline-block;
			margin-top: 2rem;
			color: #fcd34d;
			text-decoration: none;
			font-weight: 600;
			transition: opacity 0.2s;

			&:hover {
				opacity: 0.8;
				text-decoration: underline;
			}
		}
	}
</style>
